version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/app-working-dir

    steps:
      # git pull
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - cci-test-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: cci-test-{{ checksum "pom.xml" }}

      # run tests
      - run: mvn test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit

      # package into a jar
      - run: mvn clean package

